import FWCore.ParameterSet.Config as cms



source = cms.Source("PoolSource",
                            fileNames = cms.untracked.vstring(
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_10_1_WxU.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_11_2_0b7.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_12_1_qMT.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_13_1_nng.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_14_1_iNI.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_15_1_HKS.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_16_1_nZX.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_17_1_bbH.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_18_1_42o.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_19_2_CrL.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_1_1_q2j.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_20_1_hga.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_21_2_eKs.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_22_1_An2.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_23_3_jPi.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_24_1_La0.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_24_3_1NF.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_25_1_ES7.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_26_1_ngx.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_27_1_JeZ.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_28_1_kF1.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_29_1_jHL.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_2_1_G99.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_30_0_0PP.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_31_0_tAF.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_32_0_9mT.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_3_1_uNd.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_4_1_VSr.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_5_1_fP2.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_6_1_XZT.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_7_1_Br7.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_8_1_GhH.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v1/trigVal_patTuple_9_1_FVe.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_10_1_xZc.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_11_3_5Uh.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_12_3_Nyj.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_13_4_K51.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_14_3_gHK.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_15_2_Flj.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_16_1_1cu.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_16_4_rXI.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_17_2_AHJ.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_18_1_Jfn.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_19_2_pjr.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_1_2_BA7.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_20_2_Wx7.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_21_1_0KW.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_22_2_mPv.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_23_2_Ka6.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_24_1_ABH.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_25_2_m6D.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_26_2_C5D.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_2_1_DHo.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_3_2_PaP.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_4_1_owo.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_5_1_D15.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_6_2_ELz.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_7_1_HR1.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_8_1_Rft.root',
                             'file:/cms/se/store/user/duggan/Collisions11/PreTechStop/SemiOfficial_v2/SingleElectron/El27_v2/trigVal_patTuple_9_3_pu8.root'
                                                             )                              )

